minibatch_size: 64

initial_finetune:
  pos_thresh: 0.7
  neg_thresh: 0.3
  pos_num: 200 #1800 #200
  neg_num: 150 # 1200 #150
  iter: 20 # 100 #20
  learning_rate: 0.0003

finetune:
  interval: 2000
  pos_thresh: 0.7
  neg_thresh: 0.3
  long_term: 100
  short_term: 10
  pos_num: 50 #30
  neg_num: 25 #15
  iter: 20 #20
  learning_rate: 0.0001

action_move:
  x: 0.03
  y: 0.03
  w: 0.03
  h: 0.03

action_history: 10
redetection:
  samples: 256 #64 # 256

predict:
  roi_zoom: 1.4
  num_action: 20
  stop_iou: 0.93
  thresh_fail: 0.50
  thresh_success: 0.50